 - name: Install a list of packages
   apt:
     pkg:
     - npm
     - nodejs
     - python3-pip

 - name: Install bottla python package
   pip:
     name: python-jenkins

 - name: Create a jenkins job using basic authentication
   community.general.jenkins_job:
     config: "{{ lookup('file', 'templates/config.xml') }}"
     name: firstpipeline Ansible
     password: "{{ jenkins_password.user_input }}"
     url: 'http://{{ ansible_host }}:8080'
     user: "{{ jenkins_username.user_input }}"
